### ISSUE TITLE
`run-shell-command` commands beginning with `sudo` hang

### ISSUE THREAD

**Issue by dannyroberts** [dimagi/commcarehq-ansible#1099]
It should either magically handle that or detect your command starts with sudo and print an error telling you what to do.

Related to https://github.com/dimagi/commcarehq-ansible/pull/1094

**Comment by millerdev** [comment]
Ha, magically handling that sounds like a cool idea. Like if the command `startswith("sudo ")`, prompt: `Hey, sudo will likely cause this command to hang. Do you want to remove that and use --become --ask-become-pass instead? [Yn]`

On `Y` (and by default) go ahead and strip `sudo ` and add the ansible options. On `n` proceed as directed for people who know what they are doing.
