### ISSUE TITLE
elasticsearch cluster.name and node.name need to be template variables

### ISSUE THREAD

**Issue by czue** [dimagi/commcarehq-ansible#26]
using the default of `elasticsearch` means that anytime another ES instance is available it will try to move data around.

node names are less important to change but useful for logging. more info here: http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_important_configuration_changes.html#_assign_names

**Comment by czue** [comment]
@dannyroberts fyi, this is almost certainly why the cluster is red. i bet some of the shards are on your dev box.

**Comment by dannyroberts** [comment]
@czue thanks! This should be easy enough to add once the server's up and running
