### ISSUE TITLE
Preindex virtual environment doesn't actually work

### ISSUE THREAD

**Issue by czue** [dimagi/commcarehq-ansible#28]
```
cchq@indiacloud4:~/www/india$ source python_env_preindex/bin/activate
(python_env)cchq@indiacloud4:~/www/india$ which python
/home/cchq/www/india/python_env/bin/python
```
note that it's pointing to `python_env` even though the `activate` command was run in the preindex directory

**Comment by dannyroberts** [comment]
Good catch. This is almost certainly because in the set up, I copy python_env to python_env_preindex. Apparently that doesn't work, presumably because there are absolute paths hardcoded within the virtualenv directory or something.

**Comment by cewing** [comment]
yes.  you can build "portable" virtualenvs that have relative path naming used, but as of the last time I checked it was considered "experimental" and I wouldn't recommend it.

**Comment by dannyroberts** [comment]
interesting. Yeah well, solved for now—wasn't so hard to recreate from scratch.
