### ISSUE TITLE
preindex localsettings gets production environment

### ISSUE THREAD

**Issue by snopoke** [dimagi/commcarehq-ansible#44]
When running localsettings the `deploy_env` is set to `production' which results in errors in the preindex localsettings:

```
EMAIL_SUBJECT_PREFIX = '[{{ deploy_env }}] '
SERVER_ENVIRONMENT = '{{ deploy_env }}'
```

**Comment by dannyroberts** [comment]
Oh. I didn't even realize that. So it seems that when creating the localsettings.py for the preindex directory, I should pass in "{{ deploy_env }}_staging" somehow. I'll look into the smoothest way to do that. Thanks!

**Comment by snopoke** [comment]
I already made a PR with a fix: https://github.com/dimagi/commcarehq-ansible/pull/46
