### ISSUE TITLE
localsettings get sent to machines that don't need them

### ISSUE THREAD

**Issue by snopoke** [dimagi/commcarehq-ansible#45]
the following machines don't need localsettings
- hqes0
- hqes1
- pqproxy0
- hqproxy3

**Comment by czue** [comment]
we run management commands (like collectstatic) on the proxy i think. we don't need localsettings for that?

**Comment by snopoke** [comment]
Oh, yea, I guess, so then its just disabling the 'preindex' envs on the proxy's

**Comment by dannyroberts** [comment]
Is there anything actively bad about having a preindex directory and/or localsettings.py file on machines that don't need them? I'd been just kind of treating that as basic setup, but can look into doing that more granularly if necessary.

**Comment by snopoke** [comment]
Not really except that the ansible tasks fail for those machines because
the directories aren't set up
