### ISSUE TITLE
touchforms role requires 'sh' module installed on target machines

### ISSUE THREAD

**Issue by snopoke** [dimagi/commcarehq-ansible#52]
While running the touchforms tasks I got this error. I installed `sh` into the venv on the control machine but still got the error so I assume that its required on the target machine (in this case `hqdjango3`).

Not sure if this is a bug in the playbook that should manage the dependency better of if we should just install `sh` in the target venv.

``````
failed: [hqtouch1.internal.commcarehq.org -> hqdjango3.internal.commcarehq.org] => {"failed": true, "parsed": false}
SUDO-SUCCESS-nsmrnyblgwercgllpkabhmyrcjhanate
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1423726181.0-11872862573104/django_user", line 9, in <module>
    import sh
ImportError: No module named sh


FATAL: all hosts have already failed -- aborting```
``````

**Comment by dannyroberts** [comment]
I think this is installed in `common_installs` (
https://github.com/dimagi/commcarehq-ansible/blob/master/ansible/roles/common_installs/tasks/main.yml#L47-47),
but that hasn't been run on hqdjango3.
