### ISSUE TITLE
Does monitoring get run?

### ISSUE THREAD

**Issue by dannyroberts** [dimagi/commcarehq-ansible#54]
Hey @TylerSheffels. Looks like in my somewhat mechanical refactoring, I moved the reference to the monitoring role here https://github.com/dimagi/commcarehq-ansible/blob/master/ansible/deploy_db.yml#L45-45, and since there's no host called `monitoring`, I think it doesn't get run. So that's my bad, but fixing it raises the following question, which probably has a simple answer.

What machine is this supposed to be run under? If it has to be run on the same machine as redis, then calling it "monitoring" seems wrong, and "redis_monitoring" seems better.

**Comment by TylerSheffels** [comment]
@dannyroberts Initially I was thinking there was more monitoring that would occur.  Currently I think this should be switched to `redis_monitoring` and only run on the redis server. #55

**Comment by dannyroberts** [comment]
Awesome, thanks!
