### ISSUE TITLE
Log rotation is ad hoc

### ISSUE THREAD

**Issue by dannyroberts** [dimagi/commcarehq-ansible#827]
The same logrotate scripts should govern all `{{ log_home }}/*.log` files, not just ones on proxy. Pillowtop and kafka for example also log there.

**Comment by emord** [comment]
@dannyroberts you should also look at /var/log/kafka es2 on softlayer got to 100% disk used today and the  kafka logs there were huge. like 11 GB with no gzipping. I resolved it for now by gziping the larger and older log files

**Comment by emord** [comment]
syslog appears to not be rotating on es2 either

**Comment by javierwilson** [comment]
I moved kafka log dir to /opt/data/kafka, disk was 99%, i will look into why logs were not rootating.
see https://github.com/dimagi/commcarehq-ansible/pull/829

**Comment by emord** [comment]
@javierwilson kafka logs were rotating. it just wasn't gzipping the old files, so there were a few old 500 MB files lying around

**Comment by javierwilson** [comment]
it seems log4j 1.2 doesn't support compression we would need log4jextras and change policy to TimeBasedRollingPolicy, or upgrade to log4j ver 2.

**Comment by dannyroberts** [comment]
I remember we looked into this for a while but did not get very far, at least when I was working on it, because of low-level details that amounted to the rotating process and the writing process needing to cooperate with each other in a way that requires special effort for each process. There must be a way to standardize this eventually (i.e. having all processes write to stdout/stderr and having another process control redirection of those streams) but even that doesn't help us for 3rd party services that manage their own logging. I'm going to close this as won't-do for now, since I don't think keeping it around is helping us.
