### ISSUE TITLE
cron spams /var/spool/mail/root when alert_email null

### ISSUE THREAD

**Issue by dannyroberts** [dimagi/commcarehq-ansible#842]
Looks like https://github.com/dimagi/commcarehq-ansible/commit/e19a887b677db22de84ab2898a747007ac9bb96e made this happen by making `/etc/cron.d/redis-restart.sh` essentially empty (?)

```
root@hqdb0:/opt/data/postgresql/9.4/main# cat /etc/cron.d/redis-restart.sh
#!/bin/bash
# Taken from http://www.akamaras.com/linux/linux-script-to-check-if-a-service-is-running-and-start-it-if-its-stopped/
```

**Comment by dannyroberts** [comment]
message in `/var/spool/mail/root` is
```
/bin/sh: 1: root: not found
```

**Comment by kaapstorm** [comment]
That does seem weird.

Could it be that when we implemented that change, we copied the system crontab to be root's crontab? This [this thread](https://ubuntuforums.org/archive/index.php/t-1035016.html) for reference.

I checked hqdb0, and sure enough, root's crontab (`/var/spool/cron/crontabs/root`) is a copy of the system crontab.

**Comment by kaapstorm** [comment]
I went ahead and ran
```
# mv /var/spool/cron/crontabs/root /root/old_crontab
```
root is no longer getting spammed, and the system crontab seems to be fine.

**Comment by dannyroberts** [comment]
Fixed permanently in https://github.com/dimagi/commcarehq-ansible/pull/891. Followup in https://github.com/dimagi/commcarehq-ansible/pull/1105
