### ISSUE TITLE
Enable stat gathering for postgres

### ISSUE THREAD

**Issue by emord** [dimagi/commcarehq-ansible#843]
@dimagi/scale-team 

I think we should enable stat gathering at least for the UCR database, maybe the others as well https://www.postgresql.org/docs/9.4/static/pgstatstatements.html It will add some overhead to queries, but the benefit is that we can use something like https://github.com/ankane/pghero to suggest indexes to add to the database.

I think it'll be most helpful for UCRs since those are user generated without knowing what the queries are going to be like. 

Alternatively we could use something like https://github.com/ankane/dexter and use slow logs which I think we already have. Would require installing https://github.com/dalibo/hypopg too.

Thoughts?

**Comment by dannyroberts** [comment]
Having visibility into what we can do to increase speed and decrease load by, say, 15% would certainly be worth taking an upfront hit of, say, 1-5%. Do you know if there's any way to gather stats only on one of every 1000 requests, or something like that? I didn't find it on a quick search of the page you linked, but I could have been searching for the wrong thing. If there's some way to reduce load by reducing the resolution of our data, that could make this even more attractive.

**Comment by emord** [comment]
@dannyroberts I just found https://github.com/dalibo/pgbadger. ran it on some prod logs and going to run some concurrent indexes there

also found some problem queries in commtrack

**Comment by snopoke** [comment]
pgbadger is pretty great, we've used it before once or twice. Not opposed to the stats gathering though.

**Comment by emord** [comment]
I've used pghero and we have the stat tracking on some of our servers
